#File di configurazione del plugin PvPUtilities
#             Fatto da Samuconfaa.
#Per info scrivermi su discord. Trovate tutto qua:
#         https://samuconfaa.it/info

flash:
  jump_distance: 5      #Distanza in blocchi del salto
  effect_duration: 5    #Durata in secondi dell'effetto speed applicato
  cooldown: 10          #Durata in secondi del cooldown prima di riutilizzare FLASH

atom:
  range: 5              #Raggio d'azione in blocchi dell'item ATOM
  cooldown: 5           #Durata in secondi del cooldown prima di riutilizzare ATOM


boost:
  cooldown: 90
  range: 20
  playercooldown: 10

squid:
  cooldown: 90
  range: 20
  playercooldown: 10

forza:
  cooldown: 90
  playercooldown: 10

pick:
  range: 4
  cooldown: 90

cesoie:
  range: 4
  cooldown: 10

setblock:
  range: 150

messages:
  flash_given: "§aHai dato Flash a {player}"
  flash_received: "§aHai ricevuto Flash"
  atom_given: "§aHai dato Atom a {player}"
  atom_received: "§aHai ricevuto Atom"
  invalid_item: "§cTipo di oggetto PvP non valido."
  player_not_found: "§cPlayer {player} non trovato o non online."
  no_permission: "§cNon hai il permesso per usare questo comando."
  incorrect_usage: "§cUtilizzo: /pvpu <flash|atom|boost|build|pick|cesoie> <player>"
  no_reload_permission: "§cNon hai il permesso di ricaricare il file di configurazione"
  reload: "§cFile di configurazione ricaricato con successo (si spera)"
  flash_cooldown_message: "§cDevi aspettare altri {seconds} secondi prima di usare Flash nuovamente!"
  atom_cooldown_message: "§cDevi aspettare altri {seconds} secondi prima di usare Atom nuovamente!"
  boost_given: "§aHai dato Anti-Boost a {player}"
  boost_received: "§aHai ricevuto Anti-Boost"
  forza_given: "§aHai dato Forza a {player}"
  forza_received: "§aHai ricevuto Forza"
  cesoie_given: "§aHai dato Cesoie a {player}"
  cesoie_received: "§aHai ricevuto Cesoie"
  boost_cooldown_message: "§cDevi aspettare altri {seconds} secondi prima di usare Anti-Boost nuovamente!"
  pick_cooldown_message: "§cDevi aspettare altri {seconds} secondi prima di usare Piccone nuovamente!"
  cesoie_cooldown_message: "§cDevi aspettare altri {seconds} secondi prima di usare Cesoie nuovamente!"
  noblock: "§cNon puoi piazzare blocchi"
  noplayer: "§cNessun player trovato nel raggio d'azione"
  noBow: "§cNon puoi utilizzare l'arco"
  cecità: "§1Sei stato reso ceco"
  pick_given: "§aHai dato Piccone a {player}"
  pick_received: "§aHai ricevuto Piccone!"
  squid_given: "§aHai dato Squid a {player}"
  squid_received: "§aHai ricevuto Squid!"
  noObsidian: "§cNon stai guardando nessun blocco di ossidiana!"
  noCobweb: "§cNon stai guardando nessuna ragnatela!"
  forzaricevuta: "§2Forza applicata correttamente"
  block_saved: "§2Blocchi salvati!"
  no_setblock_permission: "§cNon hai i permessi per fare questo!"




items:
  flash:
    name: "§b§lFlash"
    lore:
      - "§7Tasto Destro per usare!"

  atom:
    name: "§6§lAtom"
    lore:
      - "§7Tasto Destro per usare!"

  antiboost:
    name: "§2§lAnti-Boost"
    lore:
      - "§7Tasto Destro per usare!"

  pick:
    name: "§4§lPiccone"
    lore:
      - "§7Tasto Destro per usare!"

  cesoie:
    name: "§6§lCesoie"
    lore:
      - "§7Tasto Destro per usare!"

  squid:
    name: "§1§lSquid"
    lore:
      - "§7Tasto Destro per usare!"

  forza:
    name: "§5§lForza"
    lore:
      - "§7Tasto Destro per usare!"

saved_blocks:
  obsidian:

  cobweb:

